/*
 * OCPP Device Service
 *
 * REST API to manage OCPP devices (e.g. Charging Stations)
 *
 * API version: v2.0.0
 * Contact: gr.szalay@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	"net/http"

	"github.com/gregszalay/ocpp-csms/device-service/db"
	log "github.com/sirupsen/logrus"
)

func GetAllChargingStations(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	list, err := db.ListChargingStations()
	if err != nil || list == nil {
		log.Error("failed to get a list of charging stations from db")
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte("Failed to get a list of charging stations"))
		return
	}

	jData, err := json.Marshal(list)
	if err != nil {
		log.Error("could not marshal charging station list json: ", err)
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte("Failed to get a list of charging stations"))
		return
	}

	w.Write(jData)
	w.WriteHeader(http.StatusOK)
	//json.NewEncoder(w).Encode(devices.ListChargingStations())

}
