/*
 * OCPP Device Service
 *
 * REST API to manage OCPP devices (e.g. Charging Stations)
 *
 * API version: v2.0.0
 * Contact: gr.szalay@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/gregszalay/ocpp-csms-common-types/devices"
	"github.com/gregszalay/ocpp-csms/device-service/db"
	log "github.com/sirupsen/logrus"
)

func CreateChargingStation(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	body, err := ioutil.ReadAll(r.Body)
	if err != nil {
		log.Error("failed to read http request body: ", err)
		return
	}

	var newChargingStation devices.ChargingStation
	if err := json.Unmarshal(body, &newChargingStation); err != nil {
		log.Error("failed to unmarshal json in http request body to ChargingStation object: ", err)
		return
	}

	log.Info("Attempting to create new charging station: ", newChargingStation)

	if err := db.CreateChargingStation(newChargingStation.Id, newChargingStation); err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		log.Error("failed to delete charging station")
		w.Write([]byte("Failed to create charging station."))
		return
	}

	w.WriteHeader(http.StatusOK)
	w.Write([]byte(fmt.Sprintf("Successfully created charging station with id %s", newChargingStation.Id)))
}
