/*
 * OCPP Device Service
 *
 * REST API to manage OCPP devices (e.g. Charging Stations)
 *
 * API version: v2.0.0
 * Contact: gr.szalay@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	"net/http"

	"github.com/gorilla/mux"
	"github.com/gregszalay/ocpp-csms/device-service/db"
	log "github.com/sirupsen/logrus"
)

func GetChargingStation(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	// get id from path parameter
	vars := mux.Vars(r)
	id, ok := vars["id"]
	if !ok {
		log.Error("failed to retrieve charging station id from URL path parameters")
	}

	log.Info("Attempting to get charging station with id ", id)

	device, err := db.GetChargingStation(id)
	if err != nil {
		log.Error("failed to get charging station ", id)
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte("Failed to get charging station."))
		return
	}
	jData, err := json.Marshal(device)
	if err != nil {
		log.Error(err)
	}
	w.WriteHeader(http.StatusOK)
	w.Write(jData)

}
