/*
 * OCPP Device Service
 *
 * REST API to manage OCPP devices (e.g. Charging Stations)
 *
 * API version: v2.0.0
 * Contact: gr.szalay@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	//http.FileServer(http.Dir("../api/index.html"))
	fmt.Fprint(w, "<a href='https://app.swaggerhub.com/apis/gregszalay/ocpp_device_service'>See API docs</a>")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"CreateChargingStation",
		strings.ToUpper("Post"),
		"/chargingstations/create",
		CreateChargingStation,
	},

	Route{
		"DeleteChargingStation",
		strings.ToUpper("Post"),
		"/chargingstations/delete/{id}",
		DeleteChargingStation,
	},

	Route{
		"GetChargingStation",
		strings.ToUpper("Get"),
		"/chargingstations/station/{id}",
		GetChargingStation,
	},

	Route{
		"GetAllChargingStations",
		strings.ToUpper("Get"),
		"/chargingstations/list",
		GetAllChargingStations,
	},

	Route{
		"UpdateChargingStation",
		strings.ToUpper("Post"),
		"/chargingstations/update/{id}",
		UpdateChargingStation,
	},
}
