/*
 * OCPP Device Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.0.0
 * Contact: gr.szalay@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package http

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gregszalay/ocpp-csms/device-service/devicedb"

	"github.com/gorilla/mux"
)

func FindChargers(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	vars := mux.Vars(r)
	id, ok := vars["chargerId"]
	if !ok {
		fmt.Println("id is missing in parameters")
	}
	fmt.Println(`id := `, id)
	device := devicedb.Get("devices", id)
	jData, err := json.Marshal(device)
	if err != nil {
		fmt.Println(err)
	}
	w.Write(jData)
}
