/*
 * OCPP Device Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.0.0
 * Contact: gr.szalay@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package http

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/chargerevolution/ocpp-device-service/chargingstations"
)

func FindAllChargers(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	chargerList := chargingstations.ListChargers()
	for _, charger := range chargerList {
		fmt.Printf("Charger:%v\n", charger)
	}
	jData, err := json.Marshal(chargerList)
	if err != nil {
		fmt.Printf("could not unmarshal json: %s\n", err)
		return
	}
	w.Write(jData)
	//json.NewEncoder(w).Encode(devices.ListChargers())
}
