/*
 * OCPP Device Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.0.0
 * Contact: gr.szalay@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package http

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"CreateNewCharger",
		strings.ToUpper("Post"),
		"/create",
		CreateNewCharger,
	},

	Route{
		"DeleteCharger",
		strings.ToUpper("Post"),
		"/delete/{chargerId}",
		DeleteCharger,
	},

	Route{
		"FindChargers",
		strings.ToUpper("Get"),
		"/charger/{chargerId}",
		FindChargers,
	},

	Route{
		"FindAllChargers",
		strings.ToUpper("Get"),
		"/list",
		FindAllChargers,
	},

	Route{
		"UpdateCharger",
		strings.ToUpper("Post"),
		"/update/{chargerId}",
		UpdateCharger,
	},
}
